version: '3.7'
services:
  server:
    build: ./ConvertService
    image: "${PROJECT_NAME}:${SERVER_NAME}"
    command: sh -c "./scripts/wait-for-it.sh db:3306 --timeout=60 --strict -- ./scripts/dev-entrypoint.sh"
    ports:
      - "${SERVER_PORT}:8000"
    environment:
      SERVER_ENV: dev
    tty: true
    volumes:
      - "./ConvertService:/home/ConvertService"
    depends_on:
      - db
    restart: always
