version: '3.7'
services:
  server:
    build: ./ConvertService
    image: "${PROJECT_NAME}:${SERVER_NAME}"
    ports:
      - "${SERVER_PORT}:8000"
    environment:
      SERVER_ENV: dev
    tty: true
    volumes:
      - "./ConvertService:/home/ConvertService"
      - "./ConvertService/staticfiles:/home/ConvertService/staticfiles"
      - "./ConvertService/static:/home/ConvertService/static"
    depends_on:
      - db
  db:
    image: mariadb:10.5
    ports:
      - "${DB_EXPORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
    volumes:
      - "db_volume:/var/lib/mysql"
      - ./db/initdb.d/create-db.sh:/docker-entrypoint-initdb.d/create-db.sh
      - ./db/data:/master
  db_test:
    image: mariadb:10.5
    ports:
      - "${TEST_DB_EXPORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}_test"
    volumes:
      - "db_test_volume:/var/lib/mysql"
      - ./db/initdb.d/create-db.sh:/docker-entrypoint-initdb.d/create-db.sh
volumes:
  db_volume:
  db_test_volume: