version: '3.7'
services:
  server:
    build: ./ConvertService
    image: "${PROJECT_NAME}:${SERVER_NAME}"
    command: sh -c "./scripts/wait-for-it.sh db:3306 --timeout=60 --strict -- ./scripts/stg-entrypoint.sh"
    ports:
      - "${SERVER_PORT}:8000"
    environment:
      SERVER_ENV: stg
    tty: true
    volumes:
      - "./ConvertService:/home/ConvertService"
      - "./ConvertService/staticfiles:/home/ConvertService/staticfiles"
      - "./ConvertService/static:/home/ConvertService/static"
    depends_on:
      - db
    restart: always